#!/usr/bin/env node

// get argument values
var op   =  process.argv[2],   		// operator for the math
	num1 = +process.argv[3], 		// first opperand
	num2 = +process.argv[4];  		// second operand 
	math = require ('./math_fail'); //import our math module 

console.log(math_fail[op](num1, num2));

